arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: L10n
output-dir: lib/l10n/generated
preferred-supported-locales:
  - en
  - fr
  - nl
nullable-getter: false
